import 'package:flutter/foundation.dart';

/// Study plan entity generated by AI tutor
@immutable
class StudyPlan {
  const StudyPlan({
    required this.id,
    required this.title,
    required this.goal,
    required this.duration,
    required this.hoursPerDay,
    required this.milestones,
    required this.dailyRoutine,
    required this.resources,
    required this.tips,
    required this.createdAt,
    this.progress = 0.0,
    this.completedMilestones = const [],
  });

  final String id;
  final String title;
  final String goal;
  final String duration;
  final int hoursPerDay;
  final List<Milestone> milestones;
  final List<DailyActivity> dailyRoutine;
  final List<String> resources;
  final List<String> tips;
  final DateTime createdAt;
  final double progress;
  final List<int> completedMilestones;

  StudyPlan copyWith({
    String? id,
    String? title,
    String? goal,
    String? duration,
    int? hoursPerDay,
    List<Milestone>? milestones,
    List<DailyActivity>? dailyRoutine,
    List<String>? resources,
    List<String>? tips,
    DateTime? createdAt,
    double? progress,
    List<int>? completedMilestones,
  }) {
    return StudyPlan(
      id: id ?? this.id,
      title: title ?? this.title,
      goal: goal ?? this.goal,
      duration: duration ?? this.duration,
      hoursPerDay: hoursPerDay ?? this.hoursPerDay,
      milestones: milestones ?? this.milestones,
      dailyRoutine: dailyRoutine ?? this.dailyRoutine,
      resources: resources ?? this.resources,
      tips: tips ?? this.tips,
      createdAt: createdAt ?? this.createdAt,
      progress: progress ?? this.progress,
      completedMilestones: completedMilestones ?? this.completedMilestones,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is StudyPlan && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}

/// A milestone in the study plan
@immutable
class Milestone {

  factory Milestone.fromJson(Map<String, dynamic> json) {
    return Milestone(
      week: json['week'] as int? ?? 1,
      title: json['title'] as String? ?? '',
      objectives: (json['objectives'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          [],
      topics: (json['topics'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          [],
      activities: (json['activities'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          [],
    );
  }
  const Milestone({
    required this.week,
    required this.title,
    required this.objectives,
    required this.topics,
    required this.activities,
  });

  final int week;
  final String title;
  final List<String> objectives;
  final List<String> topics;
  final List<String> activities;

  Map<String, dynamic> toJson() {
    return {
      'week': week,
      'title': title,
      'objectives': objectives,
      'topics': topics,
      'activities': activities,
    };
  }
}

/// A daily activity in the study routine
@immutable
class DailyActivity {

  factory DailyActivity.fromJson(Map<String, dynamic> json) {
    return DailyActivity(
      time: json['time'] as String? ?? '',
      duration: json['duration'] as int? ?? 30,
      activity: json['activity'] as String? ?? '',
    );
  }
  const DailyActivity({
    required this.time,
    required this.duration,
    required this.activity,
  });

  final String time;
  final int duration; // in minutes
  final String activity;

  Map<String, dynamic> toJson() {
    return {
      'time': time,
      'duration': duration,
      'activity': activity,
    };
  }
}

/// Essay feedback entity
@immutable
class EssayFeedback {
  const EssayFeedback({
    required this.id,
    required this.essayTitle,
    required this.overallScore,
    required this.summary,
    required this.sections,
    required this.strengths,
    required this.areasForImprovement,
    required this.additionalResources,
    required this.createdAt,
  });

  final String id;
  final String essayTitle;
  final int overallScore;
  final String summary;
  final Map<String, FeedbackSection> sections;
  final List<String> strengths;
  final List<String> areasForImprovement;
  final List<String> additionalResources;
  final DateTime createdAt;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is EssayFeedback && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;
}

/// A section of feedback
@immutable
class FeedbackSection {

  factory FeedbackSection.fromJson(Map<String, dynamic> json) {
    return FeedbackSection(
      score: json['score'] as int? ?? 0,
      feedback: json['feedback'] as String? ?? '',
      suggestions: (json['suggestions'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          [],
    );
  }
  const FeedbackSection({
    required this.score,
    required this.feedback,
    required this.suggestions,
  });

  final int score;
  final String feedback;
  final List<String> suggestions;

  Map<String, dynamic> toJson() {
    return {
      'score': score,
      'feedback': feedback,
      'suggestions': suggestions,
    };
  }
}
