// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// SECURITY NOTE: Firebase API keys in mobile apps are designed to be "public"
// and are safe to include in client-side code. Security is enforced through:
// 1. Firebase Security Rules (Firestore, Storage, etc.)
// 2. Firebase App Check (validates requests come from your app)
// 3. Firebase Authentication (user-level access control)
//
// IMPORTANT: Ensure Firebase Security Rules are properly configured:
// - Firestore: Only authenticated users can read/write their own data
// - Storage: Restrict access based on authentication
// - Enable Firebase App Check in production for additional protection
//
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQye53D40DWtgZqkaq1RsisQNJGidgAXU',
    appId: '1:785682493330:android:98ff7b643466bbd6b05b4b',
    messagingSenderId: '785682493330',
    projectId: 'geo-master-app',
    storageBucket: 'geo-master-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA4jr8_DvjwPo4KwPIQIhH53TQTQk7qLI',
    appId: '1:785682493330:ios:a5b7c8c82a9d68f3b05b4b',
    messagingSenderId: '785682493330',
    projectId: 'geo-master-app',
    storageBucket: 'geo-master-app.firebasestorage.app',
    iosBundleId: 'com.geomaster.geoMaster',
    iosClientId: '785682493330-nod84g7bc34k2av9l59f991pecq8da13.apps.googleusercontent.com',
  );
}
